let studentDetailsList=new Object();
studentDetailsList.name='Arul';
studentDetailsList.age=21;
studentDetailsList.gender='male';
studentDetailsList.course='CSE';
studentDetailsList.state='tamil nadu';
studentDetailsList.district='chennai';
studentDetailsList.pincode=6000028;
console.log(studentDetailsList);
console.log(studentDetailsList.name);