let educationalDetailsOfSchooling = {};
educationalDetailsOfSchooling.institutionsSpecification = {};
educationalDetailsOfSchooling.educationType = {};
educationalDetailsOfSchooling.educationalSpecification = {};
educationalDetailsOfSchooling.institutionsSpecification.one = ['Govt Middel School', 'Devarambur'];
educationalDetailsOfSchooling.institutionsSpecification.two = ['Govt Hr Sec School', 'Kottaiyiruppu'];
educationalDetailsOfSchooling.institutionsSpecification.three = ['Chendhuran College of Engineering & Technology', 'Pudukkottai'];
educationalDetailsOfSchooling.educationType.one = "primaryEducation";
educationalDetailsOfSchooling.educationType.two = "higherSecondaryEducation";
educationalDetailsOfSchooling.educationType.three = "higherEducation";
educationalDetailsOfSchooling.educationalSpecification = [];
let objectStandard_1 = {};
objectStandard_1.educationType = 'one';
objectStandard_1.standard = 1;
objectStandard_1.academicYear = '2004-2005';
objectStandard_1.status = 'pass';
objectStandard_1.mark = 150;
objectStandard_1.yearlyMarkPercentage = 45;
objectStandard_1.yearlyAttandancePercentage = 99;
objectStandard_1.educationalInstitutionsSpecification = 'one';
educationalDetailsOfSchooling.educationalSpecification.push(objectStandard_1);
let objectStandard_2 = {};
objectStandard_2.educationType = 'one';
objectStandard_2.standard = 2;
objectStandard_2.academicYear = '2005-2006';
objectStandard_2.status = 'pass';
objectStandard_2.mark = 175;
objectStandard_2.yearlyMarkPercentage = 50;
objectStandard_2.yearlyAttandancePercentage = 98;
objectStandard_2.educationalInstitutionsSpecification = 'one';
educationalDetailsOfSchooling.educationalSpecification.push(objectStandard_2);
let objectStandard_3 = {};
objectStandard_3.educationType = 'one';
objectStandard_3.standard = 3;
objectStandard_3.academicYear = '2006-2007 ';
objectStandard_3.status = 'pass';
objectStandard_3.mark = 225;
objectStandard_3.yearlyMarkPercentage = 65;
objectStandard_3.yearlyAttandancePercentage = 95;
objectStandard_3.educationalInstitutionsSpecification = 'one';
educationalDetailsOfSchooling.educationalSpecification.push(objectStandard_3);
let objectStandard_4 = {};
objectStandard_4.educationType = 'one';
objectStandard_4.standard = 4;
objectStandard_4.academicYear = '2007-2008 ';
objectStandard_4.status = 'pass';
objectStandard_4.mark = 345;
objectStandard_4.yearlyMarkPercentage = 69;
objectStandard_4.yearlyAttandancePercentage = 96;
objectStandard_4.educationalInstitutionsSpecification = 'one';
educationalDetailsOfSchooling.educationalSpecification.push(objectStandard_4);
let objectStandard_5 = {};
objectStandard_5.educationType = 'one';
objectStandard_5.standard = 5;
objectStandard_5.academicYear = '2008-2009 ';
objectStandard_5.status = 'pass';
objectStandard_5.mark = 360;
objectStandard_5.yearlyMarkPercentage = 72;
objectStandard_5.yearlyAttandancePercentage = 95;
objectStandard_5.educationalInstitutionsSpecification = 'one';
educationalDetailsOfSchooling.educationalSpecification.push(objectStandard_5);
let objectStandard_6 = {};
objectStandard_6.educationType = 'one';
objectStandard_6.standard = 6;
objectStandard_6.academicYear = '2009-2010 ';
objectStandard_6.status = 'pass';
objectStandard_6.mark = 375;
objectStandard_6.yearlyMarkPercentage = 75;
objectStandard_6.yearlyAttandancePercentage = 96;
objectStandard_6.educationalInstitutionsSpecification = 'one';
educationalDetailsOfSchooling.educationalSpecification.push(objectStandard_6);
let objectStandard_7 = {};
objectStandard_7.educationType = 'one';
objectStandard_7.standard = 7;
objectStandard_7.academicYear = '2010-2011 ';
objectStandard_7.status = 'pass';
objectStandard_7.mark = 366;
objectStandard_7.yearlyMarkPercentage = 73;
objectStandard_7.yearlyAttandancePercentage = 94;
objectStandard_7.educationalInstitutionsSpecification = 'one';
educationalDetailsOfSchooling.educationalSpecification.push(objectStandard_7);
let objectStandard_8 = {};
objectStandard_8.educationType = 'one';
objectStandard_8.standard = 8;
objectStandard_8.academicYear = '2011-2012 ';
objectStandard_8.status = 'pass';
objectStandard_8.mark = 370;
objectStandard_8.yearlyMarkPercentage = 74;
objectStandard_8.yearlyAttandancePercentage = 96;
objectStandard_8.educationalInstitutionsSpecification = 'one';
educationalDetailsOfSchooling.educationalSpecification.push(objectStandard_8);
let objectStandard_9 = {};
objectStandard_9.educationType = 'two';
objectStandard_9.standard = 9;
objectStandard_9.academicYear = '2012-2013 ';
objectStandard_9.status = 'pass';
objectStandard_9.mark = 430;
objectStandard_9.yearlyMarkPercentage = 86;
objectStandard_9.yearlyAttandancePercentage = 93;
objectStandard_9.educationalInstitutionsSpecification = 'two';
educationalDetailsOfSchooling.educationalSpecification.push(objectStandard_9);
let objectStandard_10 = {};
objectStandard_10.educationType = 'two';
objectStandard_10.standard = 10;
objectStandard_10.academicYear = '2013-2014 ';
objectStandard_10.status = 'pass';
objectStandard_10.mark = 386;
objectStandard_10.yearlyMarkPercentage = 77;
objectStandard_10.yearlyAttandancePercentage = 90;
objectStandard_10.educationalInstitutionsSpecification = 'two';
educationalDetailsOfSchooling.educationalSpecification.push(objectStandard_10);
let objectStandard_11 = {};
objectStandard_11.educationType = 'two';
objectStandard_11.standard = 11;
objectStandard_11.academicYear = '2014-2015 ';
objectStandard_11.status = 'pass';
objectStandard_11.mark = 786;
objectStandard_11.yearlyMarkPercentage = 69;
objectStandard_11.yearlyAttandancePercentage = 85;
objectStandard_11.educationalInstitutionsSpecification = 'two';
educationalDetailsOfSchooling.educationalSpecification.push(objectStandard_11);
let objectStandard_12 = {};
objectStandard_12.educationType = 'two';
objectStandard_12.standard = 12;
objectStandard_12.academicYear = '2015-2016 ';
objectStandard_12.status = 'pass';
objectStandard_12.mark = 672;
objectStandard_12.yearlyMarkPercentage = 62;
objectStandard_12.yearlyAttandancePercentage = 89;
objectStandard_12.educationalInstitutionsSpecification = 'two';
educationalDetailsOfSchooling.educationalSpecification.push(objectStandard_12);
let objectFirstYear = {};
objectFirstYear.educationType = 'three';
objectFirstYear.yearOfStudy = 'firstYear';
objectFirstYear.academicYear = '2016-2017';
objectFirstYear.CGPA = 6.9;
objectFirstYear.yearlyMarkPercentage = 65;
objectFirstYear.yearlyAttandancePercentage = 90;
objectFirstYear.educationalInstitutionsSpecification = 'three';
educationalDetailsOfSchooling.educationalSpecification.push(objectFirstYear);
let objectSecondYear = {};
objectSecondYear.educationType = 'three';
objectSecondYear.yearOfStudy = 'secondYear';
objectSecondYear.academicYear = '2017-2018';
objectSecondYear.CGPA = 7.4;
objectSecondYear.yearlyMarkPercentage = 73;
objectSecondYear.yearlyAttandancePercentage = 88;
objectSecondYear.educationalInstitutionsSpecification = 'three';
educationalDetailsOfSchooling.educationalSpecification.push(objectSecondYear);
let objectThirdYear = {};
objectThirdYear.educationType = 'three';
objectThirdYear.yearOfStudy = 'thirdYear';
objectThirdYear.academicYear = '2018-2019';
objectThirdYear.CGPA = 6.8;
objectThirdYear.yearlyMarkPercentage = 70;
objectThirdYear.yearlyAttandancePercentage = 75;
objectThirdYear.educationalInstitutionsSpecification = 'three';
educationalDetailsOfSchooling.educationalSpecification.push(objectThirdYear);
let objectFinalYear = {};
objectFinalYear.educationType = 'three';
objectFinalYear.yearOfStudy = 'finalYear';
objectFinalYear.academicYear = '2019-2020';
objectFinalYear.CGPA = 7.1;
objectFinalYear.yearlyMarkPercentage = 65;
objectFinalYear.yearlyAttandancePercentage = 85;
objectFinalYear.educationalInstitutionsSpecification = 'three';
educationalDetailsOfSchooling.educationalSpecification.push(objectFinalYear);
console.log(educationalDetailsOfSchooling);